language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.2

notifications:
  email: false

after_success:
    - julia -e 'import Pkg; cd(Pkg.dir("Clp")); Pkg.add("Coverage"); import Coverage; Codecov.submit(Codecov.process_folder())'

